services:
  frontend:
    build:
      context: ./dp-angular-app
      dockerfile: ./Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - backend

  backend:
    build:
      context: ./DiplomovaPraca
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./json_files:/app/json_files
      - ./Genetic/images:/app/images
      - ./Genetic/results:/app/results

  genetic:
    build:
      context: ./Genetic
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./Genetic/images:/app/images
      - ./Genetic/results:/app/results

  auto-cpu: # Pridaná služba auto-cpu
    build: ./stable-diffusion-webui-docker/services/AUTOMATIC1111
    image: sd-auto:72
    environment:
      - CLI_ARGS=--no-half --precision full --allow-code --enable-insecure-extension-access --api
    ports:
      - "${WEBUI_PORT:-7860}:7860"
    volumes:
      - ./data:/data
      - ./output:/output
      - ./Genetic/images:/app/images
      - genetic-results:/app/results
    stop_signal: SIGKILL
    tty: true


volumes:
  genetic-images:
  genetic-results:
